Ray worker pid: 41049
Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1034, in _get_next_task_from_raylet
    task = self.raylet_client.get_task()
  File "python/ray/_raylet.pyx", line 245, in ray._raylet.RayletClient.get_task
  File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
Exception: [RayletClient] Raylet connection closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1051, in main_loop
    task = self._get_next_task_from_raylet()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1034, in _get_next_task_from_raylet
    task = self.raylet_client.get_task()
KeyboardInterrupt
