Ray worker pid: 47201
2019-08-13 11:54:28,208	WARNING worker.py:343 -- WARNING: Falling back to serializing objects of type <class 'torch.nn.backends.thnn.THNNFunctionBackend'> by using pickle. This may be inefficient.
2019-08-13 11:54:28,238	WARNING worker.py:343 -- WARNING: Falling back to serializing objects of type <class 'torch.Size'> by using pickle. This may be inefficient.
Exception in thread ray_import_thread:
Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/import_thread.py", line 69, in _run
    msg = import_pubsub_client.get_message()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3135, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

Traceback (most recent call last):
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/workers/default_worker.py", line 98, in <module>
    ray.worker.global_worker.main_loop()
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1052, in main_loop
    self._wait_for_and_process_task(task)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 1003, in _wait_for_and_process_task
    self._process_task(task, execution_info)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/worker.py", line 908, in _process_task
    self.actors[key], *arguments)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/ray/function_manager.py", line 792, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/beast/srikar/apex/rl/algos/td3.py", line 329, in update_and_evaluate
    self.update_eval_model()
  File "/home/beast/srikar/apex/rl/algos/td3.py", line 390, in update_eval_model
    current_Q1, current_Q2 = self.critic(state, action)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beast/srikar/apex/rl/policies/td3_actor_critic.py", line 81, in forward
    x1 = self.ln2(x1)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/torch/nn/modules/normalization.py", line 157, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "/home/beast/anaconda3/envs/srikar/lib/python3.6/site-packages/torch/nn/functional.py", line 1725, in layer_norm
    torch.backends.cudnn.enabled)
KeyboardInterrupt
